import {useCallback,useEffect,useState} from 'react';
import {Link,useParams,useSearchParams} from 'react-router-dom';
import {journeyApi} from '../journey-api';
import {useResource} from '../hooks/useResource';
import {useAction} from '../hooks/useAction';
import {useLocale} from '../hooks/useLocale';
import {PageTitle,date,money} from '../components/Domain';
import {Button,Dialog,EmptyState,InlineNotice,Skeleton,StatusBadge} from '../components/ui';
import {RequestProgress} from '../components/RequestProgress';
import './ClinicianOffers.css';
export function ClinicianOffers(){
  const {w}=useLocale();const [search,setSearch]=useSearchParams();const view=search.get('view')==='history'?'History':'Active';const [page,setPage]=useState(0);
  const resource=useResource(useCallback(()=>journeyApi.clinicianOffers(page,view),[page,view]));
  useEffect(()=>{const timer=setInterval(()=>void resource.refresh(),5000);return()=>clearInterval(timer);},[resource.refresh]);
  return <><PageTitle title={w('Your offers')} description={w('Private quotes and outcomes, from response to appointment.')} action={<Link className="button secondary" to="/clinician/requests">{w('Open request inbox')}</Link>}/><div className="segmented offers-view-tabs" data-tour="clinician-offers" aria-label={w('Offer views')}>{(['Active','History'] as const).map(tab=><Button key={tab} aria-pressed={tab===view} variant={tab===view?'primary':'secondary'} onClick={()=>{setSearch(tab==='History'?{view:'history'}:{});setPage(0);}}>{w(tab)}</Button>)}</div>
    {resource.error?<InlineNotice tone="danger">{w('Your offers could not be loaded.')} <Button variant="secondary" onClick={()=>void resource.refresh()}>{w('Retry')}</Button></InlineNotice>:!resource.data?<Skeleton/>:resource.data.items.length?<><div className="table-scroll private-offers-table"><table><thead><tr>{['Patient','Service','Proposed time','Total fee','Outcome',''].map((label,index)=><th key={index}>{w(label)}</th>)}</tr></thead><tbody>{resource.data.items.map(item=><tr key={item.id}><td><strong>{item.patient_label}</strong></td><td>{item.category}<p>{item.duration_minutes} {w('minutes')} · {w(item.consultation_format==='audio'?'Audio':'Video')}</p></td><td>{date(item.start,item.timezone)}<p>{item.timezone}</p></td><td>ETB {money(item.price_minor)}</td><td><StatusBadge>{w(item.state==='Superseded'?'Not selected':item.state)}</StatusBadge></td><td><Link className="text-link" to={'/clinician/offers/'+item.id}>{w('View offer')}</Link></td></tr>)}</tbody></table></div><div className="private-offers-cards">{resource.data.items.map(item=><article key={item.id}><header><h2>{item.patient_label}</h2><StatusBadge>{w(item.state==='Superseded'?'Not selected':item.state)}</StatusBadge></header><p>{item.category} · {item.duration_minutes} {w('minutes')}</p><p>{date(item.start,item.timezone)} · {item.timezone}</p><strong>ETB {money(item.price_minor)}</strong><Link className="text-link" to={'/clinician/offers/'+item.id}>{w('View offer')}</Link></article>)}</div></>:<EmptyState title={w(view==='Active'?'No active offers.':'No closed offers yet.')}>{w('Respond to an eligible request to propose a session. Your quote stays private.')}</EmptyState>}
    {resource.data&&<div className="actions offers-pagination"><Button variant="secondary" disabled={page===0} onClick={()=>setPage(page-1)}>{w('Previous')}</Button><span>{w('Page')} {page+1}</span><Button variant="secondary" disabled={!resource.data.has_more} onClick={()=>setPage(page+1)}>{w('More offers')}</Button></div>}
  </>;
}
export function ClinicianOfferDetail(){
  const {offerId=''}=useParams();const {w}=useLocale();const resource=useResource(useCallback(()=>journeyApi.clinicianOffer(offerId),[offerId]));const action=useAction();const [withdraw,setWithdraw]=useState(false);
  useEffect(()=>{const timer=setInterval(()=>void resource.refresh(),5000);return()=>clearInterval(timer);},[resource.refresh]);
  if(resource.error)return <InlineNotice tone="danger">{w((resource.errorDetail as {code?:string}|null)?.code==='request_offer_unavailable'?'This offer is unavailable. Only your own offers can be viewed.':'This offer could not be loaded. Check your connection or sign in again.')} <Button variant="secondary" onClick={()=>void resource.refresh()}>{w('Retry')}</Button><Link className="text-link" to="/clinician/offers">{w('Your offers')}</Link></InlineNotice>;
  if(!resource.data)return <Skeleton/>;const item=resource.data.items[0];
  return <><Link className="text-link" to={'/clinician/offers'+(item.state==='Active'?'':'?view=history')}>{w('Back to your offers')}</Link><PageTitle title={w('Offer details')} description={w('Only your own quote is shown. Other clinician offers stay private.')}/><RequestProgress state={item.state} clinician/>
    <section className="private-offer-detail"><header><h2>{item.patient_label}</h2><StatusBadge>{w(item.state==='Superseded'?'Not selected':item.state)}</StatusBadge></header><dl className="request-summary-facts">{[[w('Service'),item.category],[w('Proposed time'),date(item.start,item.timezone)+' · '+item.timezone],[w('Duration'),item.duration_minutes+' '+w('minutes')],[w('Format'),w(item.consultation_format==='audio'?'Audio':'Video')],[w('Total fee'),'ETB '+money(item.price_minor)],[w('Price basis'),w(item.price_source==='custom'?'Custom quote':'Published fee')],[w('Offer expiry'),date(item.valid_until,item.timezone)]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>
      {item.state==='Active'&&<Button variant="secondary" onClick={()=>setWithdraw(true)}>{w('Withdraw offer')}</Button>}{item.state==='Accepted'&&item.appointment&&<Link className="button primary" to={'/clinician/consultations/'+item.appointment}>{w('Open consultation details')}</Link>}
    </section><Dialog open={withdraw} onOpenChange={value=>{if(!action.busy)setWithdraw(value);}} title={w('Withdraw this offer?')} description={w('The patient will no longer be able to accept this quote.')}><div className="actions"><Button variant="secondary" disabled={action.busy} onClick={()=>setWithdraw(false)}>{w('Keep offer')}</Button><Button variant="danger" loading={action.busy} onClick={()=>void action.run(async()=>{await journeyApi.withdrawOffer(item.id);setWithdraw(false);await resource.refresh();})}>{w('Withdraw offer')}</Button></div>{action.error&&<InlineNotice tone="danger">{action.error}</InlineNotice>}</Dialog></>;
}
