// Captures synthetic invited-review routes from the built Frappe app; secrets stay in the mode-600 site fixture.
const {chromium}=require('playwright'),fs=require('node:fs'),assert=require('node:assert/strict');
const root=process.env.TELE_TENA_REVIEW_SITE_PATH,fixture=JSON.parse(fs.readFileSync(root+'/private/tele_tena_review_seed.json','utf8')),creds=JSON.parse(fs.readFileSync(root+'/private/tele_tena_review_accounts.json','utf8'));
const path=require('node:path');
const base=process.env.TELE_TENA_BROWSER_BASE||'http://127.0.0.1:8017/teletena',out=process.env.TELE_TENA_SCREENSHOT_DIR||path.resolve(__dirname,'../docs/screenshots/next-design-update/current-review'),widths=[320,390,720,768,1440];fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch({headless:true});try{const p=await b.newPage({viewport:{width:1440,height:950}});p.setDefaultTimeout(8000);p.setDefaultNavigationTimeout(8000);
async function shot(name,path){await p.goto(base+path,{waitUntil:'domcontentloaded'});await p.locator('main h1').first().waitFor().catch(()=>{});await p.waitForTimeout(150);for(const width of widths){await p.setViewportSize({width,height:900});await p.evaluate(()=>document.fonts.ready);const result=await p.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:innerWidth}));await p.screenshot({path:`${out}/${name}-${width}.png`,fullPage:true});assert.ok(result.scroll<=width+1,`${name} has page overflow at ${width}px (${result.scroll}px)`)}console.log('PASS: '+name+' rendered at five responsive widths')}
async function login(role){await p.goto(base+'/sign-in',{waitUntil:'domcontentloaded'});if(await p.getByRole('button',{name:'Use email instead',exact:true}).count())await p.getByRole('button',{name:'Use email instead',exact:true}).click();if(await p.getByRole('button',{name:'Use password instead',exact:true}).count())await p.getByRole('button',{name:'Use password instead',exact:true}).click();await p.getByLabel('Email',{exact:true}).fill(fixture.users[role]);await p.getByLabel('Password',{exact:true}).fill(creds[fixture.users[role]]);await p.getByRole('button',{name:'Sign in',exact:true}).click();await p.getByRole('button',{name:'Sign out',exact:true}).waitFor()}
async function logout(){const response=p.waitForResponse(r=>r.url().includes('/api/method/frappe.handler.logout'));await p.getByRole('button',{name:'Sign out',exact:true}).click();await response;}
await shot('homepage','/');await shot('sign-in','/sign-in');
await login('patient');for(const [n,r] of [['patient-home','/patient'],['discovery','/patient/discovery'],['patient-booking','/patient/book/'+fixture.offering],['patient-appointments','/patient/appointments'],['patient-account','/patient/account'],['payments','/patient/payments'],['patient-consultation','/patient/consultations/'+fixture.appointment]])await shot(n,r);
await logout();await login('clinician');for(const [n,r] of [['clinician-today','/clinician'],['clinician-appointments','/clinician/appointments'],['availability','/clinician/availability'],['services','/clinician/services'],['clinician-account','/clinician/account'],['care-directory','/clinician/care'],['earnings','/clinician/earnings'],['clinician-consultation','/clinician/consultations/'+fixture.appointment]])await shot(n,r);
await logout();await login('reviewer');for(const [n,r] of [['admin-applications','/admin'],['admin-scopes','/admin/scopes'],['admin-disputes','/admin/financial-disputes']])await shot(n,r);
}finally{await b.close()}})().catch(e=>{console.error('Route matrix failed ('+e.name+')');process.exitCode=1});
